### PR TITLE
Load wp-cli-stubs with scanFiles:

### PR DESCRIPTION
**Pull request by szepeviktor**
**Description**

Answer to https://github.com/wearerequired/traduttore/pull/124#issuecomment-853866115

### CODE REVIEW

**Comment by szepeviktor** [comment]
@ocean90 Is it okay for you?

kép

**Comment by szepeviktor** [comment]
To resolve those

```php
          		global $wp_filesystem;
        
          		if ( ! $wp_filesystem instanceof \WP_Filesystem_Base ) {
```

(a simple `!` is for boolean variables)

**Comment by ocean90** [comment]
In [master the messages are already ignored](https://github.com/wearerequired/traduttore/blob/d82da84e7787e18844dcd251a677a3ca695d4afb/phpstan.neon.dist#L26-L31) but we can also use a stricter check as a follow-up.

So the solution is using `scanFiles` instead of `bootstrapFiles`? @swissspidy feel free to merge with your branch if it looks good to you too.

**Comment by swissspidy** [comment]
Let's give it a try 👍

**Pull request merged**
